import type { Tool } from "../../types";

const curl: Tool = {
  id: "curl",
  name: "cURL",
  binary: "curl",
  category: "Utility",
  summary: "Craft and inspect HTTP requests from the command line.",
  docsUrl: "https://curl.se/docs/manpage.html",
  install: "sudo apt install curl",
  fields: [
    {
      id: "method",
      label: "Method (-X)",
      kind: "select",
      group: "Request",
      clearable: true,
      options: [
        { id: "get", label: "GET", tokens: ["-X", "GET"] },
        { id: "post", label: "POST", tokens: ["-X", "POST"] },
        { id: "put", label: "PUT", tokens: ["-X", "PUT"] },
        { id: "delete", label: "DELETE", tokens: ["-X", "DELETE"] },
        { id: "patch", label: "PATCH", tokens: ["-X", "PATCH"] },
      ],
    },
    {
      id: "data",
      label: "Body (-d)",
      kind: "text",
      group: "Request",
      valueFlag: "-d",
      placeholder: "user=admin&pass=1234",
    },
    {
      id: "header",
      label: "Header (-H)",
      kind: "text",
      group: "Request",
      valueFlag: "-H",
      placeholder: "Authorization: Bearer ...",
    },
    {
      id: "userAgent",
      label: "User-Agent (-A)",
      kind: "text",
      group: "Request",
      valueFlag: "-A",
      placeholder: "Mozilla/5.0",
    },
    {
      id: "includeHeaders",
      label: "Include headers (-i)",
      kind: "toggle",
      group: "Output",
      onTokens: ["-i"],
    },
    {
      id: "headOnly",
      label: "Headers only (-I)",
      kind: "toggle",
      group: "Output",
      onTokens: ["-I"],
    },
    {
      id: "verbose",
      label: "Verbose (-v)",
      kind: "toggle",
      group: "Output",
      onTokens: ["-v"],
    },
    {
      id: "silent",
      label: "Silent (-s)",
      kind: "toggle",
      group: "Output",
      onTokens: ["-s"],
    },
    {
      id: "saveTo",
      label: "Save to file (-o)",
      kind: "text",
      group: "Output",
      valueFlag: "-o",
      placeholder: "response.html",
    },
    {
      id: "insecure",
      label: "Insecure TLS (-k)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-k"],
    },
    {
      id: "follow",
      label: "Follow redirects (-L)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-L"],
    },
    {
      id: "url",
      label: "URL",
      kind: "text",
      hero: true,
      contextKey: "URL",
      positional: true,
      required: true,
      placeholder: "https://target/",
    },
  ],
  presets: [
    { id: "verbose", label: "Verbose GET", set: { verbose: true, follow: true } },
    { id: "head", label: "Headers only", set: { headOnly: true } },
    { id: "post", label: "POST form", set: { method: "post", data: "user=admin&pass=1234" } },
  ],
};

export default curl;
