import type { Tool } from "../../types";

const ffuf: Tool = {
  id: "ffuf",
  name: "ffuf",
  binary: "ffuf",
  category: "Web",
  summary: "Fast web fuzzer for directories, files, parameters and vhosts.",
  docsUrl: "https://github.com/ffuf/ffuf",
  install: "sudo apt install ffuf",
  fields: [
    {
      id: "url",
      label: "URL",
      kind: "text",
      hero: true,
      contextKey: "RHOST",
      valueFlag: "-u",
      template: "http://{value}/FUZZ",
      required: true,
      placeholder: "10.10.10.5",
      help: "FUZZ marks where words are injected. Bound to RHOST.",
    },
    {
      id: "wordlist",
      label: "Wordlist",
      kind: "text",
      contextKey: "WORDLIST",
      valueFlag: "-w",
      required: true,
      placeholder: "/usr/share/wordlists/dirb/common.txt",
    },
    {
      id: "extensions",
      label: "Extensions",
      kind: "text",
      group: "Discovery",
      valueFlag: "-e",
      placeholder: ".php,.html,.txt",
    },
    {
      id: "matchCodes",
      label: "Match codes (-mc)",
      kind: "text",
      group: "Filters",
      valueFlag: "-mc",
      placeholder: "200,204,301,302,307,401,403",
    },
    {
      id: "filterCodes",
      label: "Filter codes (-fc)",
      kind: "text",
      group: "Filters",
      valueFlag: "-fc",
      placeholder: "404",
    },
    {
      id: "filterSize",
      label: "Filter size (-fs)",
      kind: "text",
      group: "Filters",
      valueFlag: "-fs",
      placeholder: "0",
      help: "Hide responses of a given byte size.",
    },
    {
      id: "filterWords",
      label: "Filter words (-fw)",
      kind: "text",
      group: "Filters",
      valueFlag: "-fw",
      placeholder: "42",
    },
    {
      id: "threads",
      label: "Threads (-t)",
      kind: "number",
      group: "Performance",
      valueFlag: "-t",
      placeholder: "40",
    },
    {
      id: "rate",
      label: "Rate limit (-rate)",
      kind: "number",
      group: "Performance",
      valueFlag: "-rate",
      placeholder: "0",
      help: "Requests per second. 0 is unlimited.",
    },
    {
      id: "recursion",
      label: "Recursion",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-recursion"],
    },
    {
      id: "autoCalibrate",
      label: "Auto-calibrate (-ac)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-ac"],
      help: "Automatically filter noisy responses.",
    },
    {
      id: "followRedirects",
      label: "Follow redirects (-r)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-r"],
    },
  ],
  presets: [
    {
      id: "dirs",
      label: "Directories",
      set: { matchCodes: "200,204,301,302,307,401,403", threads: "40" },
    },
    {
      id: "files",
      label: "Files + extensions",
      set: { extensions: ".php,.html,.txt", matchCodes: "200,301,302" },
    },
    {
      id: "recurse",
      label: "Recursive",
      set: { recursion: true, autoCalibrate: true },
    },
  ],
};

export default ffuf;
