import type { Tool } from "../../types";

const hydra: Tool = {
  id: "hydra",
  name: "Hydra",
  binary: "hydra",
  category: "Passwords",
  summary: "Online brute-force login cracker for many network services.",
  docsUrl: "https://github.com/vanhauser-thc/thc-hydra",
  install: "sudo apt install hydra",
  fields: [
    {
      id: "user",
      label: "Username (-l)",
      kind: "text",
      group: "Credentials",
      contextKey: "USER",
      valueFlag: "-l",
      placeholder: "admin",
    },
    {
      id: "userList",
      label: "User list (-L)",
      kind: "text",
      group: "Credentials",
      valueFlag: "-L",
      placeholder: "users.txt",
    },
    {
      id: "password",
      label: "Password (-p)",
      kind: "text",
      group: "Credentials",
      contextKey: "PASS",
      valueFlag: "-p",
      placeholder: "password123",
    },
    {
      id: "passList",
      label: "Password list (-P)",
      kind: "text",
      group: "Credentials",
      contextKey: "WORDLIST",
      valueFlag: "-P",
      placeholder: "/usr/share/wordlists/rockyou.txt",
    },
    {
      id: "threads",
      label: "Tasks (-t)",
      kind: "number",
      group: "Performance",
      valueFlag: "-t",
      placeholder: "16",
    },
    {
      id: "port",
      label: "Port (-s)",
      kind: "number",
      group: "Performance",
      contextKey: "RPORT",
      valueFlag: "-s",
      placeholder: "22",
    },
    {
      id: "stopOnFound",
      label: "Stop on first (-f)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-f"],
    },
    {
      id: "verbose",
      label: "Verbose (-vV)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-vV"],
    },
    {
      id: "host",
      label: "Target",
      kind: "text",
      hero: true,
      contextKey: "RHOST",
      positional: true,
      required: true,
      placeholder: "10.10.10.5",
    },
    {
      id: "service",
      label: "Service",
      kind: "select",
      positional: true,
      defaultOption: "ssh",
      options: [
        { id: "ssh", label: "ssh", tokens: ["ssh"] },
        { id: "ftp", label: "ftp", tokens: ["ftp"] },
        { id: "http-get", label: "http-get", tokens: ["http-get"] },
        { id: "http-get-form", label: "http-get-form", tokens: ["http-get-form"] },
        { id: "http-post-form", label: "http-post-form", tokens: ["http-post-form"] },
        { id: "smb", label: "smb", tokens: ["smb"] },
        { id: "rdp", label: "rdp", tokens: ["rdp"] },

        { id: "mysql", label: "mysql", tokens: ["mysql"] },
        { id: "postgres", label: "postgres", tokens: ["postgres"] },
      ],
    },
    {
      id: "formString",
      label: "Form string (login forms)",
      kind: "text",
      positional: true,
      placeholder: "/login:user=^USER^&pass=^PASS^:F=incorrect",
      help: "Only for http-get-form / http-post-form. Format is path:body:F=failure-text. ^USER^ and ^PASS^ are substituted from your username/password lists.",
    },
  ],
  presets: [
    {
      id: "http-post-form",
      label: "HTTP POST form + rockyou",
      description: "Brute-force a login form. Edit the path, field names and failure text to match the target.",
      set: {
        service: "http-post-form",
        user: "admin",
        passList: "/usr/share/wordlists/rockyou.txt",
        formString: "/login:username=^USER^&password=^PASS^:F=incorrect",
      },
    },
    {
      id: "ssh-rockyou",
      label: "SSH + rockyou",

      set: { service: "ssh", passList: "/usr/share/wordlists/rockyou.txt", threads: "16" },
    },
    {
      id: "ftp-rockyou",
      label: "FTP + rockyou",
      set: { service: "ftp", passList: "/usr/share/wordlists/rockyou.txt" },
    },
  ],
};

export default hydra;
