import type { Tool } from "../../types";

const nmap: Tool = {
  id: "nmap",
  name: "Nmap",
  binary: "nmap",
  category: "Reconnaissance",
  summary: "Network scanner for host discovery, port scanning and service detection.",
  docsUrl: "https://nmap.org/book/man.html",
  install: "sudo apt install nmap",
  fields: [
    {
      id: "target",
      label: "Target",
      kind: "text",
      hero: true,
      contextKey: "RHOST",
      positional: true,
      required: true,
      placeholder: "10.10.10.5  or  10.10.10.0/24",
      help: "Host, range or CIDR. Bound to RHOST.",
    },
    {
      id: "scanType",
      label: "Scan type",
      kind: "select",
      group: "Scan",
      clearable: true,
      options: [
        { id: "syn", label: "SYN stealth", tokens: ["-sS"], explain: "Half-open scan (needs root). Fast and quiet." },
        { id: "connect", label: "TCP connect", tokens: ["-sT"], explain: "Full TCP handshake. No root needed." },
        { id: "udp", label: "UDP", tokens: ["-sU"], explain: "Scan UDP ports (slower)." },
        { id: "ping", label: "Ping sweep", tokens: ["-sn"], explain: "Host discovery only, no port scan." },
      ],
    },
    {
      id: "ports",
      label: "Ports",
      kind: "text",
      group: "Scan",
      valueFlag: "-p",
      placeholder: "22,80,443  or  1-1000",
      help: "Specific ports or ranges.",
    },
    {
      id: "allPorts",
      label: "All 65535 ports",
      kind: "toggle",
      group: "Scan",
      onTokens: ["-p-"],
      help: "Scan every TCP port.",
    },
    {
      id: "topPorts",
      label: "Top ports",
      kind: "number",
      group: "Scan",
      valueFlag: "--top-ports",
      placeholder: "100",
    },
    {
      id: "timing",
      label: "Speed",
      kind: "select",
      group: "Scan",
      clearable: true,
      options: [
        { id: "t2", label: "Polite (T2)", tokens: ["-T2"], explain: "Slower, gentler on the target." },
        { id: "t3", label: "Normal (T3)", tokens: ["-T3"] },
        { id: "t4", label: "Aggressive (T4)", tokens: ["-T4"], explain: "Faster, good on stable networks." },
        { id: "t5", label: "Insane (T5)", tokens: ["-T5"], explain: "Fastest, may miss results." },
      ],
    },
    {
      id: "serviceVersion",
      label: "Service versions (-sV)",
      kind: "toggle",
      group: "Detection",
      onTokens: ["-sV"],
      help: "Probe open ports for software versions.",
    },
    {
      id: "defaultScripts",
      label: "Default scripts (-sC)",
      kind: "toggle",
      group: "Detection",
      onTokens: ["-sC"],
      help: "Run the safe default NSE script set.",
    },
    {
      id: "osDetect",
      label: "OS detection (-O)",
      kind: "toggle",
      group: "Detection",
      onTokens: ["-O"],
    },
    {
      id: "aggressive",
      label: "Aggressive (-A)",
      kind: "toggle",
      group: "Detection",
      onTokens: ["-A"],
      help: "Enables -sV, -sC, -O and traceroute together.",
    },
    {
      id: "skipPing",
      label: "Skip host discovery (-Pn)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-Pn"],
      help: "Treat the host as up. Useful when ping is blocked.",
    },
    {
      id: "openOnly",
      label: "Open ports only",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["--open"],
    },
    {
      id: "maxRate",
      label: "Max rate (pkts/s)",
      kind: "number",
      group: "Behaviour",
      valueFlag: "--max-rate",
      placeholder: "1000",
      help: "Upper bound on packet rate. Lower is quieter.",
    },
    {
      id: "verbose",
      label: "Verbose (-v)",
      kind: "toggle",
      group: "Behaviour",
      onTokens: ["-v"],
    },
    {
      id: "outFile",
      label: "Save output (-oN)",
      kind: "text",
      group: "Output",
      valueFlag: "-oN",
      placeholder: "scan.txt",
    },
  ],
  presets: [
    {
      id: "quick",
      label: "Quick scan",
      description: "Top 1000 ports, fast timing.",
      set: { scanType: "syn", timing: "t4", ports: "1-1000" },
    },
    {
      id: "full",
      label: "Full + versions",
      description: "All ports with service and script detection.",
      set: { scanType: "syn", allPorts: true, serviceVersion: true, defaultScripts: true },
    },
    {
      id: "udp",
      label: "UDP top 100",
      set: { scanType: "udp", topPorts: "100" },
    },
    {
      id: "aggr",
      label: "Aggressive",
      set: { aggressive: true, timing: "t4", skipPing: true },
    },
  ],
};

export default nmap;
